/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrearNegocioRouteImport } from './routes/crear-negocio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessSlugIndexRouteImport } from './routes/$businessSlug/index'
import { Route as BusinessSlugMisTurnosRouteImport } from './routes/$businessSlug/mis-turnos'
import { Route as BusinessSlugCheckoutRouteImport } from './routes/$businessSlug/checkout'
import { Route as BusinessSlugAdminRouteRouteImport } from './routes/$businessSlug/admin/route'
import { Route as BusinessSlugAdminIndexRouteImport } from './routes/$businessSlug/admin/index'
import { Route as ApiWebhooksMercadopagoRouteImport } from './routes/api/webhooks/mercadopago'
import { Route as BusinessSlugAdminTurnosRouteImport } from './routes/$businessSlug/admin/turnos'
import { Route as BusinessSlugAdminSuscripcionRouteImport } from './routes/$businessSlug/admin/suscripcion'
import { Route as BusinessSlugAdminServiciosRouteImport } from './routes/$businessSlug/admin/servicios'
import { Route as BusinessSlugAdminProfesionalesRouteImport } from './routes/$businessSlug/admin/profesionales'
import { Route as BusinessSlugAdminEstadisticasRouteImport } from './routes/$businessSlug/admin/estadisticas'
import { Route as BusinessSlugAdminConfiguracionRouteImport } from './routes/$businessSlug/admin/configuracion'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearNegocioRoute = CrearNegocioRouteImport.update({
  id: '/crear-negocio',
  path: '/crear-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugIndexRoute = BusinessSlugIndexRouteImport.update({
  id: '/$businessSlug/',
  path: '/$businessSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugMisTurnosRoute = BusinessSlugMisTurnosRouteImport.update({
  id: '/$businessSlug/mis-turnos',
  path: '/$businessSlug/mis-turnos',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugCheckoutRoute = BusinessSlugCheckoutRouteImport.update({
  id: '/$businessSlug/checkout',
  path: '/$businessSlug/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugAdminRouteRoute = BusinessSlugAdminRouteRouteImport.update({
  id: '/$businessSlug/admin',
  path: '/$businessSlug/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugAdminIndexRoute = BusinessSlugAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessSlugAdminRouteRoute,
} as any)
const ApiWebhooksMercadopagoRoute = ApiWebhooksMercadopagoRouteImport.update({
  id: '/api/webhooks/mercadopago',
  path: '/api/webhooks/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessSlugAdminTurnosRoute = BusinessSlugAdminTurnosRouteImport.update({
  id: '/turnos',
  path: '/turnos',
  getParentRoute: () => BusinessSlugAdminRouteRoute,
} as any)
const BusinessSlugAdminSuscripcionRoute =
  BusinessSlugAdminSuscripcionRouteImport.update({
    id: '/suscripcion',
    path: '/suscripcion',
    getParentRoute: () => BusinessSlugAdminRouteRoute,
  } as any)
const BusinessSlugAdminServiciosRoute =
  BusinessSlugAdminServiciosRouteImport.update({
    id: '/servicios',
    path: '/servicios',
    getParentRoute: () => BusinessSlugAdminRouteRoute,
  } as any)
const BusinessSlugAdminProfesionalesRoute =
  BusinessSlugAdminProfesionalesRouteImport.update({
    id: '/profesionales',
    path: '/profesionales',
    getParentRoute: () => BusinessSlugAdminRouteRoute,
  } as any)
const BusinessSlugAdminEstadisticasRoute =
  BusinessSlugAdminEstadisticasRouteImport.update({
    id: '/estadisticas',
    path: '/estadisticas',
    getParentRoute: () => BusinessSlugAdminRouteRoute,
  } as any)
const BusinessSlugAdminConfiguracionRoute =
  BusinessSlugAdminConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => BusinessSlugAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crear-negocio': typeof CrearNegocioRoute
  '/login': typeof LoginRoute
  '/$businessSlug/admin': typeof BusinessSlugAdminRouteRouteWithChildren
  '/$businessSlug/checkout': typeof BusinessSlugCheckoutRoute
  '/$businessSlug/mis-turnos': typeof BusinessSlugMisTurnosRoute
  '/$businessSlug/': typeof BusinessSlugIndexRoute
  '/$businessSlug/admin/configuracion': typeof BusinessSlugAdminConfiguracionRoute
  '/$businessSlug/admin/estadisticas': typeof BusinessSlugAdminEstadisticasRoute
  '/$businessSlug/admin/profesionales': typeof BusinessSlugAdminProfesionalesRoute
  '/$businessSlug/admin/servicios': typeof BusinessSlugAdminServiciosRoute
  '/$businessSlug/admin/suscripcion': typeof BusinessSlugAdminSuscripcionRoute
  '/$businessSlug/admin/turnos': typeof BusinessSlugAdminTurnosRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/$businessSlug/admin/': typeof BusinessSlugAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crear-negocio': typeof CrearNegocioRoute
  '/login': typeof LoginRoute
  '/$businessSlug/checkout': typeof BusinessSlugCheckoutRoute
  '/$businessSlug/mis-turnos': typeof BusinessSlugMisTurnosRoute
  '/$businessSlug': typeof BusinessSlugIndexRoute
  '/$businessSlug/admin/configuracion': typeof BusinessSlugAdminConfiguracionRoute
  '/$businessSlug/admin/estadisticas': typeof BusinessSlugAdminEstadisticasRoute
  '/$businessSlug/admin/profesionales': typeof BusinessSlugAdminProfesionalesRoute
  '/$businessSlug/admin/servicios': typeof BusinessSlugAdminServiciosRoute
  '/$businessSlug/admin/suscripcion': typeof BusinessSlugAdminSuscripcionRoute
  '/$businessSlug/admin/turnos': typeof BusinessSlugAdminTurnosRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/$businessSlug/admin': typeof BusinessSlugAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crear-negocio': typeof CrearNegocioRoute
  '/login': typeof LoginRoute
  '/$businessSlug/admin': typeof BusinessSlugAdminRouteRouteWithChildren
  '/$businessSlug/checkout': typeof BusinessSlugCheckoutRoute
  '/$businessSlug/mis-turnos': typeof BusinessSlugMisTurnosRoute
  '/$businessSlug/': typeof BusinessSlugIndexRoute
  '/$businessSlug/admin/configuracion': typeof BusinessSlugAdminConfiguracionRoute
  '/$businessSlug/admin/estadisticas': typeof BusinessSlugAdminEstadisticasRoute
  '/$businessSlug/admin/profesionales': typeof BusinessSlugAdminProfesionalesRoute
  '/$businessSlug/admin/servicios': typeof BusinessSlugAdminServiciosRoute
  '/$businessSlug/admin/suscripcion': typeof BusinessSlugAdminSuscripcionRoute
  '/$businessSlug/admin/turnos': typeof BusinessSlugAdminTurnosRoute
  '/api/webhooks/mercadopago': typeof ApiWebhooksMercadopagoRoute
  '/$businessSlug/admin/': typeof BusinessSlugAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crear-negocio'
    | '/login'
    | '/$businessSlug/admin'
    | '/$businessSlug/checkout'
    | '/$businessSlug/mis-turnos'
    | '/$businessSlug/'
    | '/$businessSlug/admin/configuracion'
    | '/$businessSlug/admin/estadisticas'
    | '/$businessSlug/admin/profesionales'
    | '/$businessSlug/admin/servicios'
    | '/$businessSlug/admin/suscripcion'
    | '/$businessSlug/admin/turnos'
    | '/api/webhooks/mercadopago'
    | '/$businessSlug/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crear-negocio'
    | '/login'
    | '/$businessSlug/checkout'
    | '/$businessSlug/mis-turnos'
    | '/$businessSlug'
    | '/$businessSlug/admin/configuracion'
    | '/$businessSlug/admin/estadisticas'
    | '/$businessSlug/admin/profesionales'
    | '/$businessSlug/admin/servicios'
    | '/$businessSlug/admin/suscripcion'
    | '/$businessSlug/admin/turnos'
    | '/api/webhooks/mercadopago'
    | '/$businessSlug/admin'
  id:
    | '__root__'
    | '/'
    | '/crear-negocio'
    | '/login'
    | '/$businessSlug/admin'
    | '/$businessSlug/checkout'
    | '/$businessSlug/mis-turnos'
    | '/$businessSlug/'
    | '/$businessSlug/admin/configuracion'
    | '/$businessSlug/admin/estadisticas'
    | '/$businessSlug/admin/profesionales'
    | '/$businessSlug/admin/servicios'
    | '/$businessSlug/admin/suscripcion'
    | '/$businessSlug/admin/turnos'
    | '/api/webhooks/mercadopago'
    | '/$businessSlug/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrearNegocioRoute: typeof CrearNegocioRoute
  LoginRoute: typeof LoginRoute
  BusinessSlugAdminRouteRoute: typeof BusinessSlugAdminRouteRouteWithChildren
  BusinessSlugCheckoutRoute: typeof BusinessSlugCheckoutRoute
  BusinessSlugMisTurnosRoute: typeof BusinessSlugMisTurnosRoute
  BusinessSlugIndexRoute: typeof BusinessSlugIndexRoute
  ApiWebhooksMercadopagoRoute: typeof ApiWebhooksMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-negocio': {
      id: '/crear-negocio'
      path: '/crear-negocio'
      fullPath: '/crear-negocio'
      preLoaderRoute: typeof CrearNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/': {
      id: '/$businessSlug/'
      path: '/$businessSlug'
      fullPath: '/$businessSlug/'
      preLoaderRoute: typeof BusinessSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/mis-turnos': {
      id: '/$businessSlug/mis-turnos'
      path: '/$businessSlug/mis-turnos'
      fullPath: '/$businessSlug/mis-turnos'
      preLoaderRoute: typeof BusinessSlugMisTurnosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/checkout': {
      id: '/$businessSlug/checkout'
      path: '/$businessSlug/checkout'
      fullPath: '/$businessSlug/checkout'
      preLoaderRoute: typeof BusinessSlugCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/admin': {
      id: '/$businessSlug/admin'
      path: '/$businessSlug/admin'
      fullPath: '/$businessSlug/admin'
      preLoaderRoute: typeof BusinessSlugAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/admin/': {
      id: '/$businessSlug/admin/'
      path: '/'
      fullPath: '/$businessSlug/admin/'
      preLoaderRoute: typeof BusinessSlugAdminIndexRouteImport
      parentRoute: typeof BusinessSlugAdminRouteRoute
    }
    '/api/webhooks/mercadopago': {
      id: '/api/webhooks/mercadopago'
      path: '/api/webhooks/mercadopago'
      fullPath: '/api/webhooks/mercadopago'
      preLoaderRoute: typeof ApiWebhooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$businessSlug/admin/turnos': {
      id: '/$businessSlug/admin/turnos'
      path: '/turnos'
      fullPath: '/$businessSlug/admin/turnos'
      preLoaderRoute: typeof BusinessSlugAdminTurnosRouteImport
      parentRoute: typeof BusinessSlugAdminRouteRoute
    }
    '/$businessSlug/admin/suscripcion': {
      id: '/$businessSlug/admin/suscripcion'
      path: '/suscripcion'
      fullPath: '/$businessSlug/admin/suscripcion'
      preLoaderRoute: typeof BusinessSlugAdminSuscripcionRouteImport
      parentRoute: typeof BusinessSlugAdminRouteRoute
    }
    '/$businessSlug/admin/servicios': {
      id: '/$businessSlug/admin/servicios'
      path: '/servicios'
      fullPath: '/$businessSlug/admin/servicios'
      preLoaderRoute: typeof BusinessSlugAdminServiciosRouteImport
      parentRoute: typeof BusinessSlugAdminRouteRoute
    }
    '/$businessSlug/admin/profesionales': {
      id: '/$businessSlug/admin/profesionales'
      path: '/profesionales'
      fullPath: '/$businessSlug/admin/profesionales'
      preLoaderRoute: typeof BusinessSlugAdminProfesionalesRouteImport
      parentRoute: typeof BusinessSlugAdminRouteRoute
    }
    '/$businessSlug/admin/estadisticas': {
      id: '/$businessSlug/admin/estadisticas'
      path: '/estadisticas'
      fullPath: '/$businessSlug/admin/estadisticas'
      preLoaderRoute: typeof BusinessSlugAdminEstadisticasRouteImport
      parentRoute: typeof BusinessSlugAdminRouteRoute
    }
    '/$businessSlug/admin/configuracion': {
      id: '/$businessSlug/admin/configuracion'
      path: '/configuracion'
      fullPath: '/$businessSlug/admin/configuracion'
      preLoaderRoute: typeof BusinessSlugAdminConfiguracionRouteImport
      parentRoute: typeof BusinessSlugAdminRouteRoute
    }
  }
}

interface BusinessSlugAdminRouteRouteChildren {
  BusinessSlugAdminConfiguracionRoute: typeof BusinessSlugAdminConfiguracionRoute
  BusinessSlugAdminEstadisticasRoute: typeof BusinessSlugAdminEstadisticasRoute
  BusinessSlugAdminProfesionalesRoute: typeof BusinessSlugAdminProfesionalesRoute
  BusinessSlugAdminServiciosRoute: typeof BusinessSlugAdminServiciosRoute
  BusinessSlugAdminSuscripcionRoute: typeof BusinessSlugAdminSuscripcionRoute
  BusinessSlugAdminTurnosRoute: typeof BusinessSlugAdminTurnosRoute
  BusinessSlugAdminIndexRoute: typeof BusinessSlugAdminIndexRoute
}

const BusinessSlugAdminRouteRouteChildren: BusinessSlugAdminRouteRouteChildren =
  {
    BusinessSlugAdminConfiguracionRoute: BusinessSlugAdminConfiguracionRoute,
    BusinessSlugAdminEstadisticasRoute: BusinessSlugAdminEstadisticasRoute,
    BusinessSlugAdminProfesionalesRoute: BusinessSlugAdminProfesionalesRoute,
    BusinessSlugAdminServiciosRoute: BusinessSlugAdminServiciosRoute,
    BusinessSlugAdminSuscripcionRoute: BusinessSlugAdminSuscripcionRoute,
    BusinessSlugAdminTurnosRoute: BusinessSlugAdminTurnosRoute,
    BusinessSlugAdminIndexRoute: BusinessSlugAdminIndexRoute,
  }

const BusinessSlugAdminRouteRouteWithChildren =
  BusinessSlugAdminRouteRoute._addFileChildren(
    BusinessSlugAdminRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrearNegocioRoute: CrearNegocioRoute,
  LoginRoute: LoginRoute,
  BusinessSlugAdminRouteRoute: BusinessSlugAdminRouteRouteWithChildren,
  BusinessSlugCheckoutRoute: BusinessSlugCheckoutRoute,
  BusinessSlugMisTurnosRoute: BusinessSlugMisTurnosRoute,
  BusinessSlugIndexRoute: BusinessSlugIndexRoute,
  ApiWebhooksMercadopagoRoute: ApiWebhooksMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
